import { LibroStock } from "./types";

export const INITIAL_LIBROS_STOCK: LibroStock[] = [
  {
    id: "lib-stock-001",
    codigo: "LIT-VAL-001",
    titulo: "Paco Yunque",
    autor: "César Vallejo",
    editorial: "Colección Plan Lector MINEDU",
    categoria: "Plan Lector Institucional",
    gradoSugerido: "4°",
    cantidadTotal: 35,
    cantidadDisponible: 35,
    ubicacion: "Estante A - Nivel 2 (Literatura Peruana)",
    estadoFisico: "Bueno",
    esPlanLector: true,
    isbn: "978-612-4012-34-1",
    observaciones: "Edición ilustrada con guía pedagógica de comprensión de lectura y valores.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-002",
    codigo: "LIT-ARG-002",
    titulo: "El Torito de la Piel Brillante",
    autor: "José María Arguedas",
    editorial: "Editorial Horizonte / MINEDU",
    categoria: "Mitos y Leyendas Andinas",
    gradoSugerido: "3°",
    cantidadTotal: 30,
    cantidadDisponible: 30,
    ubicacion: "Estante A - Nivel 3 (Literatura Andina)",
    estadoFisico: "Excelente",
    esPlanLector: true,
    isbn: "978-612-4122-12-8",
    observaciones: "Narrativa quechua tradicional adaptada para educación primaria.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-003",
    codigo: "LIT-ARG-003",
    titulo: "Warma Kuyay (Amor de Niño)",
    autor: "José María Arguedas",
    editorial: "Biblioteca Escolar Ayacucho",
    categoria: "Literatura Andina",
    gradoSugerido: "6°",
    cantidadTotal: 28,
    cantidadDisponible: 28,
    ubicacion: "Estante A - Nivel 3 (Literatura Andina)",
    estadoFisico: "Bueno",
    esPlanLector: true,
    isbn: "978-9972-205-55-4",
    observaciones: "Cuento clásico ambientado en la serranía de Lucanas y Puquio.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-004",
    codigo: "LIT-IZQ-004",
    titulo: "El Bagrecico",
    autor: "Francisco Izquierdo Ríos",
    editorial: "MINEDU - Módulo de Lectura",
    categoria: "Cuentos Amazónicos",
    gradoSugerido: "3°",
    cantidadTotal: 30,
    cantidadDisponible: 30,
    ubicacion: "Estante B - Nivel 1 (Cuentos Infantiles)",
    estadoFisico: "Bueno",
    esPlanLector: true,
    isbn: "978-612-4200-88-2",
    observaciones: "Fomenta la perseverancia y el cuidado de los ríos y naturaleza.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-005",
    codigo: "LIT-VALD-005",
    titulo: "El Caballero Carmelo",
    autor: "Abraham Valdelomar",
    editorial: "Editorial San Marcos Escolar",
    categoria: "Narrativa Peruana",
    gradoSugerido: "5°",
    cantidadTotal: 32,
    cantidadDisponible: 32,
    ubicacion: "Estante A - Nivel 1 (Clásicos Peruanos)",
    estadoFisico: "Excelente",
    esPlanLector: true,
    isbn: "978-612-302-111-9",
    observaciones: "Obra fundamental para el análisis de valores familiares y respeto.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-006",
    codigo: "LIT-COL-006",
    titulo: "Cholito en los Andes Mágicos",
    autor: "Óscar Colchado Lucio",
    editorial: "Alfaguara Infantil",
    categoria: "Literatura Infantil",
    gradoSugerido: "4°",
    cantidadTotal: 25,
    cantidadDisponible: 25,
    ubicacion: "Estante B - Nivel 2 (Novela Infantil)",
    estadoFisico: "Bueno",
    esPlanLector: true,
    isbn: "978-612-4050-43-9",
    observaciones: "Aventuras basadas en la mitología andina (pishtaco, ichic ollco).",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-007",
    codigo: "LIT-UNIV-007",
    titulo: "El Principito",
    autor: "Antoine de Saint-Exupéry",
    editorial: "Editorial Panamericana",
    categoria: "Literatura Universal",
    gradoSugerido: "5°",
    cantidadTotal: 30,
    cantidadDisponible: 30,
    ubicacion: "Estante C - Nivel 1 (Literatura Universal)",
    estadoFisico: "Excelente",
    esPlanLector: true,
    isbn: "978-958-30-0015-7",
    observaciones: "Texto clásico con ilustraciones a color para desarrollo socioemocional.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-008",
    codigo: "MIN-CTA-008",
    titulo: "Ciencia y Tecnología 5° - Cuaderno de Autoaprendizaje",
    autor: "Ministerio de Educación (MINEDU)",
    editorial: "MINEDU Perú",
    categoria: "Textos Escolares MINEDU",
    gradoSugerido: "5°",
    cantidadTotal: 40,
    cantidadDisponible: 40,
    ubicacion: "Estante D - Nivel 2 (Textos MINEDU)",
    estadoFisico: "Bueno",
    esPlanLector: false,
    isbn: "978-612-01-3320-1",
    observaciones: "Dotación oficial dotada para experimentos de indagación científica.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-009",
    codigo: "MIN-MAT-009",
    titulo: "Matemática 4° Primaria - Resolución de Problemas",
    autor: "Ministerio de Educación (MINEDU)",
    editorial: "MINEDU Perú",
    categoria: "Textos Escolares MINEDU",
    gradoSugerido: "4°",
    cantidadTotal: 38,
    cantidadDisponible: 38,
    ubicacion: "Estante D - Nivel 1 (Textos MINEDU)",
    estadoFisico: "Bueno",
    esPlanLector: false,
    isbn: "978-612-01-3315-7",
    observaciones: "Contiene situaciones lúdicas y material manipulativo complementario.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-010",
    codigo: "ENC-NAT-010",
    titulo: "Atlas Visual de Flora y Fauna del Perú y los Andes",
    autor: "Antonio Brack Egg",
    editorial: "Editorial Bruño",
    categoria: "Enciclopedias y Consulta",
    gradoSugerido: "Todos los grados",
    cantidadTotal: 15,
    cantidadDisponible: 15,
    ubicacion: "Mesa de Consulta Central / Estante E",
    estadoFisico: "Excelente",
    esPlanLector: false,
    isbn: "978-9972-1-0845-6",
    observaciones: "Libro de gran formato para investigación sobre biodiversidad y conservación.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-011",
    codigo: "LIT-QUE-011",
    titulo: "Fábulas y Adivinanzas Quechuas Chanka",
    autor: "Tradición Oral de Ayacucho / DREA",
    editorial: "Ediciones Regionales Ayacucho",
    categoria: "Cultura e Interculturalidad",
    gradoSugerido: "2°",
    cantidadTotal: 25,
    cantidadDisponible: 25,
    ubicacion: "Estante A - Nivel 4 (Interculturalidad Bilingüe)",
    estadoFisico: "Excelente",
    esPlanLector: true,
    isbn: "978-612-4511-09-5",
    observaciones: "Bilingüe castellano - quechua chanka para rescate de saberes ancestrales.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-012",
    codigo: "LIT-PRI-012",
    titulo: "La Niña de la Sombra de Colores",
    autor: "César Vega Herrera",
    editorial: "Colección Cuentos de la Patria Chica",
    categoria: "Plan Lector Institucional",
    gradoSugerido: "1°",
    cantidadTotal: 30,
    cantidadDisponible: 30,
    ubicacion: "Estante B - Nivel 1 (Primer Ciclo)",
    estadoFisico: "Excelente",
    esPlanLector: true,
    isbn: "978-612-4015-12-0",
    observaciones: "Lectura inicial con letra script e ilustraciones a color para 1° de primaria.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-013",
    codigo: "LIT-SEL-013",
    titulo: "Cuentos Infantiles y Leyendas del Perú",
    autor: "Ciro Alegría",
    editorial: "Editorial Mantaro Escolar",
    categoria: "Plan Lector Institucional",
    gradoSugerido: "1°",
    cantidadTotal: 25,
    cantidadDisponible: 25,
    ubicacion: "Estante B - Nivel 1 (Primer Ciclo)",
    estadoFisico: "Bueno",
    esPlanLector: true,
    isbn: "978-612-4015-18-2",
    observaciones: "Adaptación pedagógica para iniciación a la comprensión lectora.",
    createdAt: new Date().toISOString()
  },
  {
    id: "lib-stock-014",
    codigo: "LIT-AND-014",
    titulo: "Cuentos Andinos y Costumbres",
    autor: "Enrique López Albújar",
    editorial: "Editorial Universitaria Andina",
    categoria: "Plan Lector Institucional",
    gradoSugerido: "6°",
    cantidadTotal: 28,
    cantidadDisponible: 28,
    ubicacion: "Estante A - Nivel 3 (Literatura Andina)",
    estadoFisico: "Excelente",
    esPlanLector: true,
    isbn: "978-9972-205-88-2",
    observaciones: "Obras clásicas seleccionadas para debate y juicio crítico en 6° grado.",
    createdAt: new Date().toISOString()
  }
];
